# Lab 5: PyTorch Introduction


## Phần 1: Khám phá Tensor

### Task 1.1: Tạo Tensor

In [2]:
import torch
import numpy as np

# Tạo tensor từ list
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(f"Tensor từ list:\n {x_data}\n")

# Tạo tensor từ NumPy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(f"Tensor từ NumPy array:\n {x_np}\n")

# Tạo tensor với các giá trị ngẫu nhiên hoặc hằng số
x_ones = torch.ones_like(x_data) # tạo tensor gồm các số 1 có cùng shape với x_data
print(f"Ones Tensor:\n {x_ones}\n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # tạo tensor ngẫu nhiên
print(f"Random Tensor:\n {x_rand}\n")

# In ra shape, dtype, và device của tensor
print(f"Shape của tensor: {x_rand.shape}")
print(f"Datatype của tensor: {x_rand.dtype}")
print(f"Device lưu trữ tensor: {x_rand.device}")

Tensor từ list:
 tensor([[1, 2],
        [3, 4]])

Tensor từ NumPy array:
 tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

Ones Tensor:
 tensor([[1, 1],
        [1, 1]])

Random Tensor:
 tensor([[0.5896, 0.3564],
        [0.5792, 0.2011]])

Shape của tensor: torch.Size([2, 2])
Datatype của tensor: torch.float32
Device lưu trữ tensor: cpu


### Task 1.2: Các phép toán trên Tensor
Thực hiện các phép toán sau:
1. Cộng x_data với chính nó
2. Nhân x_data với 5
3. Nhân ma trận x_data với x_data.T (ma trận chuyển vị)

In [3]:
# 1. Cộng x_data với chính nó
result_add = x_data + x_data
print(f"x_data + x_data:\n {result_add}\n")

# 2. Nhân x_data với 5
result_mul = x_data * 5
print(f"x_data * 5:\n {result_mul}\n")

# 3. Nhân ma trận x_data với x_data.T (ma trận chuyển vị)
result_matmul = x_data @ x_data.T
print(f"x_data @ x_data.T:\n {result_matmul}\n")

# Kiểm tra kích thước
print(f"x_data shape: {x_data.shape}")
print(f"x_data.T shape: {x_data.T.shape}")
print(f"Result shape: {result_matmul.shape}")

x_data + x_data:
 tensor([[2, 4],
        [6, 8]])

x_data * 5:
 tensor([[ 5, 10],
        [15, 20]])

x_data @ x_data.T:
 tensor([[ 5, 11],
        [11, 25]])

x_data shape: torch.Size([2, 2])
x_data.T shape: torch.Size([2, 2])
Result shape: torch.Size([2, 2])


### Task 1.3: Indexing và Slicing
Từ tensor x_data:
1. Lấy ra hàng đầu tiên
2. Lấy ra cột thứ hai
3. Lấy ra giá trị ở hàng thứ hai, cột thứ hai

In [4]:
print(f"x_data:\n {x_data}\n")

# 1. Lấy ra hàng đầu tiên
first_row = x_data[0]
print(f"Hàng đầu tiên: {first_row}\n")

# 2. Lấy ra cột thứ hai
second_col = x_data[:, 1]
print(f"Cột thứ hai: {second_col}\n")

# 3. Lấy ra giá trị ở hàng thứ hai, cột thứ hai
value = x_data[1, 1]
print(f"Giá trị ở hàng thứ hai, cột thứ hai: {value}\n")

x_data:
 tensor([[1, 2],
        [3, 4]])

Hàng đầu tiên: tensor([1, 2])

Cột thứ hai: tensor([2, 4])

Giá trị ở hàng thứ hai, cột thứ hai: 4



### Task 1.4: Thay đổi hình dạng Tensor


In [5]:
# Tạo tensor với shape (4, 4)
tensor_4x4 = torch.rand(4, 4)
print(f"Tensor ban đầu (4, 4):\n {tensor_4x4}\n")
print(f"Shape ban đầu: {tensor_4x4.shape}\n")

# Sử dụng view để thay đổi thành (16, 1)
tensor_16x1_view = tensor_4x4.view(16, 1)
print(f"Tensor sau khi dùng view (16, 1):\n {tensor_16x1_view}\n")
print(f"Shape sau view: {tensor_16x1_view.shape}\n")

# Sử dụng reshape để thay đổi thành (16, 1)
tensor_16x1_reshape = tensor_4x4.reshape(16, 1)
print(f"Tensor sau khi dùng reshape (16, 1):\n {tensor_16x1_reshape}\n")
print(f"Shape sau reshape: {tensor_16x1_reshape.shape}")

Tensor ban đầu (4, 4):
 tensor([[0.5319, 0.0081, 0.0570, 0.2965],
        [0.1486, 0.7180, 0.8490, 0.4835],
        [0.0409, 0.9057, 0.1895, 0.1153],
        [0.2077, 0.4706, 0.6286, 0.0418]])

Shape ban đầu: torch.Size([4, 4])

Tensor sau khi dùng view (16, 1):
 tensor([[0.5319],
        [0.0081],
        [0.0570],
        [0.2965],
        [0.1486],
        [0.7180],
        [0.8490],
        [0.4835],
        [0.0409],
        [0.9057],
        [0.1895],
        [0.1153],
        [0.2077],
        [0.4706],
        [0.6286],
        [0.0418]])

Shape sau view: torch.Size([16, 1])

Tensor sau khi dùng reshape (16, 1):
 tensor([[0.5319],
        [0.0081],
        [0.0570],
        [0.2965],
        [0.1486],
        [0.7180],
        [0.8490],
        [0.4835],
        [0.0409],
        [0.9057],
        [0.1895],
        [0.1153],
        [0.2077],
        [0.4706],
        [0.6286],
        [0.0418]])

Shape sau reshape: torch.Size([16, 1])


## Phần 2: Tự động tính Đạo hàm với autograd

### Task 2.1: Thực hành với autograd

In [6]:
# Tạo một tensor và yêu cầu tính đạo hàm cho nó
x = torch.ones(1, requires_grad=True)
print(f"x: {x}")

# Thực hiện một phép toán
y = x + 2
print(f"y: {y}")

# y được tạo ra từ một phép toán có x, nên nó cũng có grad_fn
print(f"grad_fn của y: {y.grad_fn}")

# Thực hiện thêm các phép toán
z = y * y * 3
print(f"z: {z}")

# Tính đạo hàm của z theo x
z.backward() # tương đương z.backward(torch.tensor(1.))

# Đạo hàm được lưu trong thuộc tính .grad
# Ta có z = 3 * (x+2)^2 => dz/dx = 6 * (x+2). Với x=1, dz/dx = 18
print(f"Đạo hàm của z theo x: {x.grad}")

x: tensor([1.], requires_grad=True)
y: tensor([3.], grad_fn=<AddBackward0>)
grad_fn của y: <AddBackward0 object at 0x00000214A9A514B0>
z: tensor([27.], grad_fn=<MulBackward0>)
Đạo hàm của z theo x: tensor([18.])


### Câu hỏi: Chuyện gì xảy ra nếu bạn gọi z.backward() một lần nữa? Tại sao?
Thử gọi z.backward() lần nữa:
Lỗi: như cell bên dưới

#### GIẢI THÍCH 
Sau khi gọi backward() lần đầu, computational graph đã bị xóa để tiết kiệm bộ nhớ.
Nếu muốn gọi backward() nhiều lần, cần sử dụng retain_graph=True


In [7]:
# Thử gọi backward() lần nữa
print("\nThử gọi z.backward() lần nữa:")
try:
    z.backward()
except RuntimeError as e:
    print(f"Lỗi: {e}")

# Demo với retain_graph=True
print("\n=== Demo với retain_graph=True ===")
x2 = torch.ones(1, requires_grad=True)
y2 = x2 + 2
z2 = y2 * y2 * 3

z2.backward(retain_graph=True)
print(f"Đạo hàm lần 1: {x2.grad}")

z2.backward(retain_graph=True)
print(f"Đạo hàm lần 2 (tích lũy): {x2.grad}")
print("\nChú ý: Đạo hàm được tích lũy (accumulated), không được ghi đè!")
print("Để reset gradient, cần gọi x.grad.zero_() hoặc optimizer.zero_grad()")


Thử gọi z.backward() lần nữa:
Lỗi: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

=== Demo với retain_graph=True ===
Đạo hàm lần 1: tensor([18.])
Đạo hàm lần 2 (tích lũy): tensor([36.])

Chú ý: Đạo hàm được tích lũy (accumulated), không được ghi đè!
Để reset gradient, cần gọi x.grad.zero_() hoặc optimizer.zero_grad()


## Phần 3: Xây dựng Mô hình đầu tiên với torch.nn

### Task 3.1: Lớp nn.Linear
Lớp nn.Linear thực hiện một phép biến đổi tuyến tính y = xA^T + b.

In [8]:
import torch.nn as nn

# Khởi tạo một lớp Linear biến đổi từ 5 chiều -> 2 chiều
linear_layer = nn.Linear(in_features=5, out_features=2)

# Tạo một tensor đầu vào mẫu
input_tensor = torch.randn(3, 5) # 3 mẫu, mỗi mẫu 5 chiều

# Truyền đầu vào qua lớp linear
output = linear_layer(input_tensor)
print(f"Input shape: {input_tensor.shape}")
print(f"Output shape: {output.shape}")
print(f"Output:\n {output}\n")

# Kiểm tra weight và bias của lớp linear
print(f"Weight shape: {linear_layer.weight.shape}")
print(f"Bias shape: {linear_layer.bias.shape}")

Input shape: torch.Size([3, 5])
Output shape: torch.Size([3, 2])
Output:
 tensor([[ 0.5697, -1.1957],
        [-0.0472,  0.1233],
        [ 0.0317,  0.2174]], grad_fn=<AddmmBackward0>)

Weight shape: torch.Size([2, 5])
Bias shape: torch.Size([2])


### Task 3.2: Lớp nn.Embedding

In [9]:
# Khởi tạo lớp Embedding cho một từ điển 10 từ, mỗi từ biểu diễn bằng vector 3 chiều
embedding_layer = nn.Embedding(num_embeddings=10, embedding_dim=3)

# Tạo một tensor đầu vào chứa các chỉ số của từ (ví dụ: một câu)
# Các chỉ số phải nhỏ hơn 10
input_indices = torch.LongTensor([1, 5, 0, 8])

# Lấy ra các vector embedding tương ứng
embeddings = embedding_layer(input_indices)
print(f"Input shape: {input_indices.shape}")
print(f"Output shape: {embeddings.shape}")
print(f"Embeddings:\n {embeddings}\n")

# Kiểm tra weight của lớp embedding (bảng tra cứu)
print(f"Embedding weight shape: {embedding_layer.weight.shape}")
print(f"Embedding weight (bảng tra cứu):\n {embedding_layer.weight}")

Input shape: torch.Size([4])
Output shape: torch.Size([4, 3])
Embeddings:
 tensor([[ 0.2134,  0.3500, -0.6019],
        [ 1.0221,  1.3374,  0.5143],
        [-0.0847, -0.4722, -0.4141],
        [-0.9459,  0.8232,  0.7120]], grad_fn=<EmbeddingBackward0>)

Embedding weight shape: torch.Size([10, 3])
Embedding weight (bảng tra cứu):
 Parameter containing:
tensor([[-0.0847, -0.4722, -0.4141],
        [ 0.2134,  0.3500, -0.6019],
        [-0.7977, -0.8090, -1.6738],
        [ 0.2901,  1.0553, -0.4287],
        [ 0.1856, -0.4887,  0.6988],
        [ 1.0221,  1.3374,  0.5143],
        [ 2.5416,  1.8051,  0.8225],
        [ 1.5355,  1.0656,  1.8903],
        [-0.9459,  0.8232,  0.7120],
        [-0.7243, -0.2706,  0.0395]], requires_grad=True)


### Task 3.3: Kết hợp thành một nn.Module

In [10]:
from torch import nn

class MyFirstModel(nn.Module):
    def __init__(self, vocab_size, embedding_dim, hidden_dim, output_dim):
        super(MyFirstModel, self).__init__()
        # Định nghĩa các lớp (layer) bạn sẽ dùng
        self.embedding = nn.Embedding(vocab_size, embedding_dim)
        self.linear = nn.Linear(embedding_dim, hidden_dim)
        self.activation = nn.ReLU() # Hàm kích hoạt
        self.output_layer = nn.Linear(hidden_dim, output_dim)
    
    def forward(self, indices):
        # Định nghĩa luồng dữ liệu đi qua các lớp
        # 1. Lấy embedding
        embeds = self.embedding(indices)
        # 2. Truyền qua lớp linear và hàm kích hoạt
        hidden = self.activation(self.linear(embeds))
        # 3. Truyền qua lớp output
        output = self.output_layer(hidden)
        return output

# Khởi tạo và kiểm tra mô hình
model = MyFirstModel(vocab_size=100, embedding_dim=16, hidden_dim=8, output_dim=2)
print("=== Thông tin mô hình ===")
print(model)
print("\n=== Kiểm tra đầu vào/đầu ra ===")

input_data = torch.LongTensor([[1, 2, 5, 9]]) # một câu gồm 4 từ
output_data = model(input_data)

print(f"Input shape: {input_data.shape}")
print(f"Model output shape: {output_data.shape}")
print(f"Model output:\n {output_data}\n")

# Đếm số tham số của mô hình
total_params = sum(p.numel() for p in model.parameters())
trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f"Tổng số tham số: {total_params}")
print(f"Số tham số có thể huấn luyện: {trainable_params}")

# Liệt kê các tham số của từng lớp
print("\n=== Chi tiết tham số của từng lớp ===")
for name, param in model.named_parameters():
    print(f"{name}: {param.shape} - {param.numel()} tham số")

=== Thông tin mô hình ===
MyFirstModel(
  (embedding): Embedding(100, 16)
  (linear): Linear(in_features=16, out_features=8, bias=True)
  (activation): ReLU()
  (output_layer): Linear(in_features=8, out_features=2, bias=True)
)

=== Kiểm tra đầu vào/đầu ra ===
Input shape: torch.Size([1, 4])
Model output shape: torch.Size([1, 4, 2])
Model output:
 tensor([[[-0.2424,  0.4812],
         [ 0.1028,  0.3434],
         [ 0.0471,  0.1080],
         [ 0.2272,  0.1676]]], grad_fn=<ViewBackward0>)

Tổng số tham số: 1754
Số tham số có thể huấn luyện: 1754

=== Chi tiết tham số của từng lớp ===
embedding.weight: torch.Size([100, 16]) - 1600 tham số
linear.weight: torch.Size([8, 16]) - 128 tham số
linear.bias: torch.Size([8]) - 8 tham số
output_layer.weight: torch.Size([2, 8]) - 16 tham số
output_layer.bias: torch.Size([2]) - 2 tham số
